// Generated by CoffeeScript 1.7.1
(function() {
  var MutationObserver;

  MutationObserver = (function() {
    function MutationObserver(callBack) {
      this.callBack = callBack;
    }

    MutationObserver.prototype.observe = function(element, options) {
      this.element = element;
      return this.interval = setInterval((function(_this) {
        return function() {
          var html;
          html = _this.element.innerHTML;
          if (_this.oldHtml == null) {
            _this.oldHtml = html;
          }
          if (html !== _this.oldHtml) {
            _this.oldHtml = html;
            
            return _this.callBack.apply(null);
          }
        };
      })(this), 10);
    };

    MutationObserver.prototype.disconnect = function() {
      return window.clearInterval(this.interval);
    };

    return MutationObserver;

  })();

  window.MutationObserver = MutationObserver;

}).call(this);
